env:
  TAG: 1.0
  GROUP: dcgsteve
  APP: publicfiles

profiles:
  - name: default

functions:

  - name: build
    run:
      - docker build . -t ${GROUP}/${APP}:${TAG}

  - name: push
    run:
      - docker push ${GROUP}/${APP}:${TAG}

  - name: all
    run:
      - $(build)
      - $(push)

  - name: testup
    run:
      - docker rm ${GROUP}/${APP}:${TAG} -f
      - docker run -d -p 8000:8000 -v ${PWD}/test:/files ${GROUP}/${APP}:${TAG}
      - curl localhost:8000

  - name: testdown
    run:
      - docker rm ${GROUP}/${APP}:${TAG} -f
