# Example compose file

version: "3.1"

services:

  app:
    container_name: public
    image: dcgsteve/publicfiles:1.0
    restart: always
    ports:
      - 8007:8000
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    volumes:
      - /data/public:/files
